language: node_js
os:
  - linux
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
compiler: clang
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
after_script:
  - 'npm run coveralls'
